### ISSUE TITLE
Unique color count

### ISSUE THREAD

**Issue by Crissov** [pornel/ImageAlpha#22]
ImageAlpha should tell me how many unique colors my image contains or it should limit the upper bound to that.

**Comment by pornel** [comment]
What would you use that information for?

**Comment by Crissov** [comment]
To not select more colors than I actually need in pictures with very few colors.

**Comment by pornel** [comment]
If the number of colors is lower than 256, then you don't need to worry about it, because:

* for everything between 17 and 256 colors PNG uses the same 8-bit representation
* packed pixels for 16 colors or less often compress worse than 8-bit
* PNG optimizers deal with that automatically

If the number of colors is higher than 256, then to figure out if that's good enough, there's no better way than looking at the actual image :)

The raw number doesn't mean much — you can have an image that has 256 different colors and tiny barely noticeable noise that bumps the count to 2000, but it'll look fine in 256. Or you can have an image with a rainbow of 300 colors that will look worse when 40 colors are removed.

**Comment by Crissov** [comment]
I see, but this is more of a user experience issue than a technical one. As a casual user I won’t know such details. Think of it as a “lossless threshold” indicator that provides a fuzzy feeling of assurance that I’m not destroying my picture without looking at it closely.

You are right of course, that a mere count cannot cover cases of similar colors – heck, reducing colors can sometimes remove prior compression artifacts (but also anti-aliasing). A histogram would help with that, but I understand that the workflow of ImageAlpha mostly relies on visual inspection.

**Comment by pornel** [comment]
If you're willing to trust an algorithm, then I suggest using ImageOptim 1.6 with lossy option, which has this "lossless threshold".
